### ISSUE TITLE
does not work with class methods

### ISSUE THREAD

**Issue by Pyrolistical** [digitaldesignlabs/es6-promisify#13]
This is the problem:
https://github.com/digitaldesignlabs/es6-promisify/blob/master/lib/promisify.js#L63

If you pass in a class method, `that` is used in apply instead of the original class instance.

I solved it by passing class instance and method name separately, e.g. `promisify(someClass, 'someMethod')` and modify `promisify.js` to
```
    return function (that, methodName, custom) {

        return function () {
            for (var _len3 = arguments.length, args = Array(_len3), _key3 = 0; _key3 < _len3; _key3++) {
                args[_key3] = arguments[_key3];
            }

            // Return the promisified function
            return new ES6Promise(function (resolve, reject) {

                // Create a Context object
                var ctx = new Context(resolve, reject, custom);

                // Append the callback bound to the context
                args.push(callback.bind(null, ctx));

                // Call the function
                that[methodName].apply(that, args);
            });
        };
    };
```

But that is a change in API.  What do you suggest?  Overload promisify and detect if second parameter is either a string or custom callback?

**Comment by mikehall314** [comment]
Use `.bind()` ?

**Comment by Pyrolistical** [comment]
Ok that would work. Probably should make a PR to es6-promisify-all to use bind when given a class
