### ISSUE TITLE
Promises with multiple arguments group args into an array

### ISSUE THREAD

**Issue by rhys-vdw** [digitaldesignlabs/es6-promisify#14]
As by design in #9, promisified functions that invoke a callback with multiple arguments are resolved as an array. This handling is confusing and unnecessary, as functions already accept more than one argument.

```js
function example(callback) {
  return callback(error, 'a', 'b');
}

promisify(example)().then(result =>
  // result -> ['a', 'b']
);

// I would expect:
promisify(example)().then((a, b) =>
  // a -> 'a'
  // b -> 'b'
);
```

This is how Bluebird's `promisify` works, and means that the callback handler is invoked consistently regardless of the number of arguments returned.

Happy to provide a PR to fix this.

**Comment by rhys-vdw** [comment]
Also consider this behaviour:

```js
const example = promisify((array, callback) =>
  callback(null, ...array);
)

example([0]).then(result => 
  // result -> 0
);

example([0, 1]).then(result => 
  // result -> [0, 1]
);
```

Sometimes the function resolves and array, sometimes it doesn't.

**Comment by mikehall314** [comment]
Hey,

I'm not sure if this is achievable, since `resolve` is only permitted to take one argument?

```js
const foo = new Promise(resolve => {
    resolve(1, 2, 3);
});

foo.then(console.log); // 1
```

I'm also not sure how calling a `then` function with multiple arguments would interact with ES7 `await`?

**Comment by rhys-vdw** [comment]
Hey, right. I wasn't aware of that restrictions. That's disappointing, but makes perfect sense in the context of `async`/`await`. In that case I agree that the current handling is the most appropriate. Thanks for the explanation!
