### ISSUE TITLE
Document a callback with multiple arguments

### ISSUE THREAD

**Issue by kumar303** [digitaldesignlabs/es6-promisify#16]
It would be nice to document what happens when you promisify a node function with a callback that takes multiple arguments. Here is an ES6 example you could maybe use:
````
import tmp from 'tmp';  // node builtin

let createTmpDir = promisify(tmp.dir);
createTmpDir()
  .then((args) => {
    let [tmpPath, removeTmpDir] = args;
    // ...
  });
````
For those unfamiliar with promises, they would expect it to look more like:
````
createTmpDir()
  .then((tmpPath, removeTmpDir) => {
    // ...
  });
````

**Comment by gunar** [comment]
I think you got it the other way around. Promises always return a single value (could be an Array of values, of course. see Promise.all()). Callbacks indeed could take more than just `(err, value)`.

**Comment by kumar303** [comment]
> I think you got it the other way around.

Was my proposed example incorrect? It was just a sample, the docs could contain any example.

> Promises always return a single value

I know but to me it was not totally obvious how `es6-promisify` would wrap a node-style function that executes a callback with multiple args. If you think it's obvious then feel free to close the bug. It should be easy to document how a callback with multiple args gets wrapped by `es6-promisify` though, it's only a couple more lines in your docs. You could copy/paste what I added here.

**Comment by gunar** [comment]
I fully agree! :+1: I'd like that documentation and actually I don't even know what es6-promisify does in this case, do you?

I have misread the description of your second snippet: "For those unfamiliar with promises, **THEY** would expect it to look more like:". Sorry :smile:

**Comment by kumar303** [comment]
> I don't even know what es6-promisify does in this case, do you?

Yes. My first example is correct, I tried it. You have to use it like this:
````javascript
import tmp from 'tmp';  // node builtin

let createTmpDir = promisify(tmp.dir);
createTmpDir()
  .then((result) => {
    let [tmpPath, removeTmpDir] = result;
    // ...
  });
````

**Comment by mikehall314** [comment]
Pull requests cheerfully accepted :)

**Comment by kumar303** [comment]
> Pull requests cheerfully accepted :)

Feel free to close the issue, it was just a suggestion. I don't have time for a patch right now. Maybe later.

**Comment by kumar303** [comment]
This issue can be closed now. I just saw the new `multiArg` feature and it seems well documented: https://github.com/digitaldesignlabs/es6-promisify#handle-callback-multiple-arguments

FWIW, I don't fully understand this change. Any reason why `multiArg: true` isn't the default behavior? I can't think of a situation where one would *expect* it to work like `multiArg: false`. It seems convenient as a shortcut but it is confusing if you need to reach multiple callback arguments. Anyway, I updated my use of `promisify()` with `{multiArg: true}` and it's working fine.
