### ISSUE TITLE
Minify bundle.

### ISSUE THREAD

**Issue by ScriptWorker** [digitaldesignlabs/es6-promisify#20]
I have a suggestion to minify bundle. At least strip comments, to make it smaller. What do you think regarding this?

In any case thank you for your work.

**Comment by mikehall314** [comment]
It's simple enough to do, but I would have expected whomever was using the library to minify the bundle as part of their build process at their end before deploying it?

**Comment by ScriptWorker** [comment]
In such case this library should be bundled with other code, I guess it is not always the case. It can be as external resource, as is. Even more - for some cases this library can be loaded without any build system.

I thought that it can be useful for someone else to get small size out of the box. In any case it is up to you. I'm closing this ticket as it is not related to any defects.
