### ISSUE TITLE
Bundling a promise polyfill is not optimal

### ISSUE THREAD

**Issue by jbrantly** [digitaldesignlabs/es6-promisify#29]
Currently this library checks to see if there is a Promise global defined and if there is not then it specifically requires() 'es6-promise'. The problem with this is that there are a bunch of Promise polyfills out there that people use. If using this library with a bundler like webpack, that require call is going to always include 'es6-promise' even if Promises have already been polyfilled elsewhere, resulting in size bloat of the bundle.

Would it be possible instead to just assume "Promise" exists and include instructions on the possible necessity of polyfilling with an example of how to do so? This would give users a lot more flexibility.

**Comment by mikehall314** [comment]
The next version of this library will not bundle a polyfill.
