### ISSUE TITLE
Add `thisArg` option usage in readme documentation

### ISSUE THREAD

**Issue by oldlam** [digitaldesignlabs/es6-promisify#31]
Suggest to add `thisArg` option usage with [`multiArgs` sample in readme documentation](https://github.com/digitaldesignlabs/es6-promisify#handle-callback-multiple-arguments)

otherwise will have to go and read the code to see how to set context while using `multiArgs`

**Comment by mikehall314** [comment]
`thisArg` is being discontinued in the next version of this lib.
