### ISSUE TITLE
`multiArgs` doesn't work in case of rejection

### ISSUE THREAD

**Issue by kilianc** [digitaldesignlabs/es6-promisify#33]
Let's say I am promisifying `exec`. I want to `.catch` the call and print stderr then throw. It seems not possible at this moment, correct?

**Comment by kbrandwijk** [comment]
I would also like all values to be returned on error as well.

**Comment by mikehall314** [comment]
This library is really only designed for the simplest cases, to avoid having to write boilerplate all the time.  In this case, I would suggest you code up something specific to your use case, or perhaps investigate the new `util.promisify` in Node 8 (which the next version of this library will likely seek to mimic).

**Comment by kbrandwijk** [comment]
It's literally a one line change vs writing my own wrapper... I don't see how this complicates anything.
https://github.com/digitaldesignlabs/es6-promisify/blob/master/lib/promisify.js#L54

**Comment by mikehall314** [comment]
The Promise standard doesn't support returning multiple values; a Promise unwraps to a single value. `multiArgs` was always a hack around this (not an especially satisfying one) and is going away in the next version of this lib.  I don't really see the value updating a feature which is going away soon. Sorry! :(
