### ISSUE TITLE
is it possible to trigger HTTP requests from this plugin?

### ISSUE THREAD

**Issue by PrithiviRajG** [digitaldesignlabs/es6-promisify#38]
I want to trigger a HTTP Get request using this plugin so I can handle the response inside then function.
Please share some sample to do like that. Thanks

**Comment by mikehall314** [comment]
Not sure how this is relevant to this library?  You want to look at something like the [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) or [node-fetch](https://github.com/bitinn/node-fetch)
